# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem 'rdoc'
gem 'yard'
gem 'puppet'
gem 'puppet-strings'
gem 'certified'
gem 'anthill-librarian-puppet'
gem 'hiera-eyaml'
